version: "3.9"

networks:
  mynetwork:

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDISHOST}
      - DB_HOST=db
    networks:
      - mynetwork

  redis:
    image: redis:7.0-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

volumes:
  postgres_data:
  redis_data:
