version: "3.9"

networks:
  mynetwork:

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - mynetwork

  redis:
    image: redis:7.0-alpine
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

volumes:
  postgres_data:
  redis_data:
